<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="drone">

    <!-- Properties -->
    <xacro:property name="frameLength" value="0.4"/>
    <xacro:property name="frameBreadth" value="0.2"/>
    <xacro:property name="frameHeight" value="0.05"/>
    <xacro:property name="frameMass" value="0.88"/>
    <xacro:property name="armLength" value="0.15"/>
    <xacro:property name="armRadius" value="0.01"/>
    <xacro:property name="armMass" value="0.02"/>
    <xacro:property name="propellerRadius" value="0.1"/>
    <xacro:property name="propellerHeight" value="0.01"/>
    <xacro:property name="propellerMass" value="0.02"/>

    <!-- Macros -->
    <xacro:macro name="slender_rod_inertial" params="length mass">
        <inertial>
        <mass value="${mass}"/>
        <inertia 
            ixx="${(1/12) * mass * (length*length)}"
            ixy="0.0"
            ixz="0.0"
            iyy="0.0"
            iyz="0.0"
            izz="${(1/12) * mass * (length*length)}"
        />
        </inertial>
    </xacro:macro>

    <xacro:macro name="rectangle_inertial" params="frameLength frameBreadth frameHeight mass *origin">
        <inertial>
            <mass value="${mass}"/>
            <xacro:insert_block name="origin"/>
            <inertia 
                ixx="${(1/12) * mass * (frameHeight*frameHeight + frameLength*frameLength)}"
                ixy="0.0"
                ixz="0.0"
                iyy="${(1/12) * mass * (frameBreadth*frameBreadth + frameHeight*frameHeight)}"
                iyz="0.0"
                izz="${(1/12) * mass * (frameLength*frameLength + frameBreadth*frameBreadth)}"
            />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial" params="radius height mass">
        <inertial>
        <mass value="${mass}"/>
        <inertia 
            ixx="${0.0833333 * mass * (3 * radius * radius + height * height)}"
            ixy="0.0"
            ixz="0.0"
            iyy="${0.0833333 * mass * (3 * radius * radius + height * height)}"
            iyz="0.0"
            izz="${0.5 * mass * radius * radius}"
        />
        </inertial>
    </xacro:macro>

    <!-- Arms -->
    <xacro:macro name="arm" params="i x y angle">
        <link name="arm${i}">
            <visual>
                <origin xyz="${armLength/2} 0 0" rpy="0 ${pi/2} 0"/>
                <geometry>
                    <cylinder radius="${armRadius}" length="${armLength}"/>
                </geometry>
                <material name="arm_material"/>
            </visual>

            <collision>
                <origin xyz="${armLength/2} 0 0" rpy="0 ${pi/2} 0"/>
                <geometry>
                    <cylinder radius="${armRadius}" length="${armLength}"/>
                </geometry>
            </collision>

            <xacro:slender_rod_inertial length="${armLength}" mass="${armMass}">
            </xacro:slender_rod_inertial>
        </link>
        
        <joint name="frame_arm${i}" type="fixed">
        <parent link="frame"/>
        <child link="arm${i}"/>
        <origin xyz="${x} ${y} 0" rpy="0 0 ${angle}"/>
        </joint>
    </xacro:macro>

    <xacro:arm i="1" x="${frameLength/2}" y="-${frameBreadth/2}" angle="-${pi/4}"/>
    <xacro:arm i="2" x="${frameLength/2}" y="${frameBreadth/2}" angle="${pi/4}"/>
    <xacro:arm i="3" x="-${frameLength/2}" y="${frameBreadth/2}" angle="${3*pi/4}"/>
    <xacro:arm i="4" x="-${frameLength/2}" y="-${frameBreadth/2}" angle="-${3*pi/4}"/>

    <!-- Propellers -->
    <xacro:macro name="propeller" params="i x y">
        <link name="propeller${i}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${propellerRadius}" length="${propellerHeight}"/>
                </geometry>
                <material name="propeller_material"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${propellerRadius}" length="${propellerHeight}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial radius="${propellerRadius}" height="${propellerHeight}" mass="${propellerMass}">
            </xacro:cylinder_inertial>

        </link>
        
        <joint name="arm${i}_propeller${i}" type="continuous">
            <parent link="arm${i}"/>
            <child link="propeller${i}"/>
            <origin xyz="${x} ${y} ${frameHeight/2 - 0.0001}" rpy="0 0 ${pi/4}"/>
            <axis xyz="0 0 1"/>
            <limit effort="0.1" velocity="10"/>
        </joint>
    </xacro:macro>

    <xacro:propeller i="1" x="${armLength}" y="0"/>
    <xacro:propeller i="2" x="${armLength}" y="0" />
    <xacro:propeller i="3" x="${armLength}" y="0" />
    <xacro:propeller i="4" x="${armLength}" y="0" />


    <!-- Frame -->
    <link name="frame">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${frameLength} ${frameBreadth} ${frameHeight}"/>
            </geometry>
            <material name="frame_material"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${frameLength} ${frameBreadth} ${frameHeight}"/>
            </geometry>
        </collision>
        <xacro:rectangle_inertial frameLength="${frameLength}" frameBreadth="${frameBreadth}" frameHeight="${frameHeight}" mass="${frameMass}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:rectangle_inertial>
    </link>

    <!-- materials -->
    <material name="frame_material">
        <color rgba="1 0.2 0.2 1"/>
    </material>
    
    <material name="arm_material">
        <color rgba="0.8 0.8 0.8 0.5"/>
    </material>
    
    <material name="propeller_material">
        <color rgba="0 0 0 0.5"/>
    </material>

</robot>